# TODO: add comprehensive and documented examples of how to use this file
# keep everything commented as this will be copied if no other config exists
# highlight "env" config is merged with root config

# explain envs and default_env
default_env = 'demo'

[env.demo]
host = "https://demo.defectdojo.org/"
user = "admin"
# password but not a secret - https://github.com/DefectDojo/django-DefectDojo/?tab=readme-ov-file#demo
password = "1Defectdojo@demo#appsec"

# [env.local]
# host = "http://localhost:8080"
# token = "..."
