templateDir: local/support/api_generation/templates.spec
additionalProperties:
  generateSourceCodeOnly: true
  packageName: defectdojo_api_generated
files:
  simple_client.mustache:
    folder: defectdojo_api_generated
    destinationFilename: simple_client.py
    templateType: SupportingFiles
