generatorName: python
templateDir: support/api_generation/custom_templates
additionalProperties:
  generateSourceCodeOnly: true
  packageName: defectdojo_api_generated
  packageUrl: https://github.com/fopina/defectdojo-api-generated
  projectName: defectdojo-api-generated
globalProperties:
  modelDocs: false
  apiDocs: false
files:
  client.mustache:
    folder: defectdojo_api_generated
    destinationFilename: client.py
    templateType: SupportingFiles
