# coding: utf-8

"""
DefectDojo API v2

DefectDojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing_extensions import Self


class CeleryQueueTaskDetail(BaseModel):
    """
    CeleryQueueTaskDetail
    """  # noqa: E501

    task_name: Optional[StrictStr] = None
    count: Optional[StrictInt] = None
    oldest_position: Optional[StrictInt] = None
    newest_position: Optional[StrictInt] = None
    oldest_eta: Optional[StrictStr] = None
    newest_eta: Optional[StrictStr] = None
    earliest_expires: Optional[StrictStr] = None
    latest_expires: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        'task_name',
        'count',
        'oldest_position',
        'newest_position',
        'oldest_eta',
        'newest_eta',
        'earliest_expires',
        'latest_expires',
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        defer_build=True,
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CeleryQueueTaskDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                'task_name',
                'count',
                'oldest_position',
                'newest_position',
                'oldest_eta',
                'newest_eta',
                'earliest_expires',
                'latest_expires',
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if oldest_eta (nullable) is None
        # and model_fields_set contains the field
        if self.oldest_eta is None and 'oldest_eta' in self.model_fields_set:
            _dict['oldest_eta'] = None

        # set to None if newest_eta (nullable) is None
        # and model_fields_set contains the field
        if self.newest_eta is None and 'newest_eta' in self.model_fields_set:
            _dict['newest_eta'] = None

        # set to None if earliest_expires (nullable) is None
        # and model_fields_set contains the field
        if self.earliest_expires is None and 'earliest_expires' in self.model_fields_set:
            _dict['earliest_expires'] = None

        # set to None if latest_expires (nullable) is None
        # and model_fields_set contains the field
        if self.latest_expires is None and 'latest_expires' in self.model_fields_set:
            _dict['latest_expires'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CeleryQueueTaskDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'task_name': obj.get('task_name'),
                'count': obj.get('count'),
                'oldest_position': obj.get('oldest_position'),
                'newest_position': obj.get('newest_position'),
                'oldest_eta': obj.get('oldest_eta'),
                'newest_eta': obj.get('newest_eta'),
                'earliest_expires': obj.get('earliest_expires'),
                'latest_expires': obj.get('latest_expires'),
            }
        )
        return _obj
