# coding: utf-8

"""
DefectDojo API v2

DefectDojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt
from typing_extensions import Self


class CeleryStatus(BaseModel):
    """
    CeleryStatus
    """  # noqa: E501

    worker_status: Optional[StrictBool] = None
    broker_status: Optional[StrictBool] = None
    queue_length: Optional[StrictInt] = None
    task_time_limit: Optional[StrictInt] = None
    task_soft_time_limit: Optional[StrictInt] = None
    task_default_expires: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = [
        'worker_status',
        'broker_status',
        'queue_length',
        'task_time_limit',
        'task_soft_time_limit',
        'task_default_expires',
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        defer_build=True,
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CeleryStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                'worker_status',
                'broker_status',
                'queue_length',
                'task_time_limit',
                'task_soft_time_limit',
                'task_default_expires',
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if queue_length (nullable) is None
        # and model_fields_set contains the field
        if self.queue_length is None and 'queue_length' in self.model_fields_set:
            _dict['queue_length'] = None

        # set to None if task_time_limit (nullable) is None
        # and model_fields_set contains the field
        if self.task_time_limit is None and 'task_time_limit' in self.model_fields_set:
            _dict['task_time_limit'] = None

        # set to None if task_soft_time_limit (nullable) is None
        # and model_fields_set contains the field
        if self.task_soft_time_limit is None and 'task_soft_time_limit' in self.model_fields_set:
            _dict['task_soft_time_limit'] = None

        # set to None if task_default_expires (nullable) is None
        # and model_fields_set contains the field
        if self.task_default_expires is None and 'task_default_expires' in self.model_fields_set:
            _dict['task_default_expires'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CeleryStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'worker_status': obj.get('worker_status'),
                'broker_status': obj.get('broker_status'),
                'queue_length': obj.get('queue_length'),
                'task_time_limit': obj.get('task_time_limit'),
                'task_soft_time_limit': obj.get('task_soft_time_limit'),
                'task_default_expires': obj.get('task_default_expires'),
            }
        )
        return _obj
