# coding: utf-8

"""
DefectDojo API v2

DefectDojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing_extensions import Annotated, Self


class FindingTemplateRequest(BaseModel):
    """
    FindingTemplateRequest
    """  # noqa: E501

    tags: Optional[List[Annotated[str, Field(min_length=1, strict=True)]]] = None
    title: Annotated[str, Field(min_length=1, strict=True, max_length=1000)]
    cwe: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    cvssv3: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=117)]] = Field(
        default=None,
        description='Common Vulnerability Scoring System version 3 (CVSSv3) score associated with this finding.',
    )
    cvssv3_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description='CVSSv3 score')
    cvssv4: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(
        default=None,
        description='Common Vulnerability Scoring System version 4 (CVSS4) score associated with this finding.',
    )
    cvssv4_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description='CVSSv4 score')
    severity: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    description: Optional[StrictStr] = None
    mitigation: Optional[StrictStr] = None
    impact: Optional[StrictStr] = None
    references: Optional[StrictStr] = None
    fix_available: Optional[StrictBool] = Field(
        default=None, description='Indicates if a fix is available for this vulnerability type'
    )
    fix_version: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None, description='Version where fix is available'
    )
    planned_remediation_version: Optional[Annotated[str, Field(strict=True, max_length=99)]] = Field(
        default=None, description='Target version for remediation'
    )
    effort_for_fixing: Optional[Annotated[str, Field(strict=True, max_length=99)]] = Field(
        default=None, description='Effort estimate for fixing (e.g., Low/Medium/High)'
    )
    steps_to_reproduce: Optional[StrictStr] = Field(
        default=None, description='Standard reproduction steps for this vulnerability type'
    )
    severity_justification: Optional[StrictStr] = Field(
        default=None, description='Explanation of why this severity level is appropriate'
    )
    component_name: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(
        default=None, description='Affected component name (e.g., library name)'
    )
    component_version: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None, description='Affected component version'
    )
    notes: Optional[StrictStr] = Field(default=None, description='Note content to add when applying this template')
    endpoints_text: Optional[StrictStr] = Field(default=None, description='Endpoint URLs (one per line)')
    __properties: ClassVar[List[str]] = [
        'tags',
        'title',
        'cwe',
        'cvssv3',
        'cvssv3_score',
        'cvssv4',
        'cvssv4_score',
        'severity',
        'description',
        'mitigation',
        'impact',
        'references',
        'fix_available',
        'fix_version',
        'planned_remediation_version',
        'effort_for_fixing',
        'steps_to_reproduce',
        'severity_justification',
        'component_name',
        'component_version',
        'notes',
        'endpoints_text',
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        defer_build=True,
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FindingTemplateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cwe (nullable) is None
        # and model_fields_set contains the field
        if self.cwe is None and 'cwe' in self.model_fields_set:
            _dict['cwe'] = None

        # set to None if cvssv3 (nullable) is None
        # and model_fields_set contains the field
        if self.cvssv3 is None and 'cvssv3' in self.model_fields_set:
            _dict['cvssv3'] = None

        # set to None if cvssv3_score (nullable) is None
        # and model_fields_set contains the field
        if self.cvssv3_score is None and 'cvssv3_score' in self.model_fields_set:
            _dict['cvssv3_score'] = None

        # set to None if cvssv4 (nullable) is None
        # and model_fields_set contains the field
        if self.cvssv4 is None and 'cvssv4' in self.model_fields_set:
            _dict['cvssv4'] = None

        # set to None if cvssv4_score (nullable) is None
        # and model_fields_set contains the field
        if self.cvssv4_score is None and 'cvssv4_score' in self.model_fields_set:
            _dict['cvssv4_score'] = None

        # set to None if severity (nullable) is None
        # and model_fields_set contains the field
        if self.severity is None and 'severity' in self.model_fields_set:
            _dict['severity'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and 'description' in self.model_fields_set:
            _dict['description'] = None

        # set to None if mitigation (nullable) is None
        # and model_fields_set contains the field
        if self.mitigation is None and 'mitigation' in self.model_fields_set:
            _dict['mitigation'] = None

        # set to None if impact (nullable) is None
        # and model_fields_set contains the field
        if self.impact is None and 'impact' in self.model_fields_set:
            _dict['impact'] = None

        # set to None if references (nullable) is None
        # and model_fields_set contains the field
        if self.references is None and 'references' in self.model_fields_set:
            _dict['references'] = None

        # set to None if fix_available (nullable) is None
        # and model_fields_set contains the field
        if self.fix_available is None and 'fix_available' in self.model_fields_set:
            _dict['fix_available'] = None

        # set to None if fix_version (nullable) is None
        # and model_fields_set contains the field
        if self.fix_version is None and 'fix_version' in self.model_fields_set:
            _dict['fix_version'] = None

        # set to None if planned_remediation_version (nullable) is None
        # and model_fields_set contains the field
        if self.planned_remediation_version is None and 'planned_remediation_version' in self.model_fields_set:
            _dict['planned_remediation_version'] = None

        # set to None if effort_for_fixing (nullable) is None
        # and model_fields_set contains the field
        if self.effort_for_fixing is None and 'effort_for_fixing' in self.model_fields_set:
            _dict['effort_for_fixing'] = None

        # set to None if steps_to_reproduce (nullable) is None
        # and model_fields_set contains the field
        if self.steps_to_reproduce is None and 'steps_to_reproduce' in self.model_fields_set:
            _dict['steps_to_reproduce'] = None

        # set to None if severity_justification (nullable) is None
        # and model_fields_set contains the field
        if self.severity_justification is None and 'severity_justification' in self.model_fields_set:
            _dict['severity_justification'] = None

        # set to None if component_name (nullable) is None
        # and model_fields_set contains the field
        if self.component_name is None and 'component_name' in self.model_fields_set:
            _dict['component_name'] = None

        # set to None if component_version (nullable) is None
        # and model_fields_set contains the field
        if self.component_version is None and 'component_version' in self.model_fields_set:
            _dict['component_version'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and 'notes' in self.model_fields_set:
            _dict['notes'] = None

        # set to None if endpoints_text (nullable) is None
        # and model_fields_set contains the field
        if self.endpoints_text is None and 'endpoints_text' in self.model_fields_set:
            _dict['endpoints_text'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FindingTemplateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'tags': obj.get('tags'),
                'title': obj.get('title'),
                'cwe': obj.get('cwe'),
                'cvssv3': obj.get('cvssv3'),
                'cvssv3_score': obj.get('cvssv3_score'),
                'cvssv4': obj.get('cvssv4'),
                'cvssv4_score': obj.get('cvssv4_score'),
                'severity': obj.get('severity'),
                'description': obj.get('description'),
                'mitigation': obj.get('mitigation'),
                'impact': obj.get('impact'),
                'references': obj.get('references'),
                'fix_available': obj.get('fix_available'),
                'fix_version': obj.get('fix_version'),
                'planned_remediation_version': obj.get('planned_remediation_version'),
                'effort_for_fixing': obj.get('effort_for_fixing'),
                'steps_to_reproduce': obj.get('steps_to_reproduce'),
                'severity_justification': obj.get('severity_justification'),
                'component_name': obj.get('component_name'),
                'component_version': obj.get('component_version'),
                'notes': obj.get('notes'),
                'endpoints_text': obj.get('endpoints_text'),
            }
        )
        return _obj
