# coding: utf-8

"""
DefectDojo API v2

DefectDojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing_extensions import Annotated, Self


class SystemSettingsRequest(BaseModel):
    """
    SystemSettingsRequest
    """  # noqa: E501

    enable_deduplication: Optional[StrictBool] = Field(
        default=None,
        description='With this setting turned on, DefectDojo deduplicates findings by comparing endpoints, cwe fields, and titles. If two findings share a URL and have the same CWE or title, DefectDojo marks the recent finding as a duplicate. When deduplication is enabled, a list of deduplicated findings is added to the engagement view.',
    )
    delete_duplicates: Optional[StrictBool] = Field(
        default=None, description='Requires next setting: maximum number of duplicates to retain.'
    )
    max_dupes: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(
        default=None,
        description='When enabled, if a single issue reaches the maximum number of duplicates, the oldest will be deleted. Duplicate will not be deleted when left empty. A value of 0 will remove all duplicates.',
    )
    email_from: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    enable_jira: Optional[StrictBool] = None
    enable_jira_web_hook: Optional[StrictBool] = Field(
        default=None,
        description='Please note: It is strongly recommended to use a secret below and / or IP whitelist the JIRA server using a proxy such as Nginx.',
    )
    disable_jira_webhook_secret: Optional[StrictBool] = Field(
        default=None, description='Allows incoming requests without a secret (discouraged legacy behaviour)'
    )
    jira_webhook_secret: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = Field(
        default=None, description='Secret needed in URL for incoming JIRA Webhook'
    )
    jira_minimum_severity: Optional[StrictStr] = Field(
        default=None,
        description='* `Critical` - Critical * `High` - High * `Medium` - Medium * `Low` - Low * `Info` - Info',
    )
    jira_labels: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None, description='JIRA issue labels space seperated'
    )
    add_vulnerability_id_to_jira_label: Optional[StrictBool] = None
    enable_github: Optional[StrictBool] = None
    enable_slack_notifications: Optional[StrictBool] = None
    slack_channel: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None, description='Optional. Needed if you want to send global notifications.'
    )
    slack_token: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None, description='Token required for interacting with Slack. Get one at https://api.slack.com/tokens'
    )
    slack_username: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(
        default=None, description='Optional. Will take your bot name otherwise.'
    )
    enable_msteams_notifications: Optional[StrictBool] = None
    msteams_url: Optional[Annotated[str, Field(strict=True, max_length=400)]] = Field(
        default=None, description='The full URL of the incoming webhook'
    )
    enable_mail_notifications: Optional[StrictBool] = None
    mail_notifications_to: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    enable_webhooks_notifications: Optional[StrictBool] = None
    webhooks_notifications_timeout: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(
        default=None, description='How many seconds will DefectDojo waits for response from webhook endpoint'
    )
    enforce_verified_status: Optional[StrictBool] = Field(
        default=None,
        description='When enabled, features such as product grading, jira integration, metrics, and reports will only interact with verified findings. This setting will override individually scoped verified toggles.',
    )
    enforce_verified_status_jira: Optional[StrictBool] = Field(
        default=None, description='When enabled, findings must have a verified status to be pushed to jira.'
    )
    enforce_verified_status_product_grading: Optional[StrictBool] = Field(
        default=None,
        description="When enabled, findings must have a verified status to be considered as part of a product's grading.",
    )
    enforce_verified_status_metrics: Optional[StrictBool] = Field(
        default=None,
        description='When enabled, findings must have a verified status to be counted in metric calculations, be included in reports, and filters.',
    )
    false_positive_history: Optional[StrictBool] = Field(
        default=None,
        description="(EXPERIMENTAL) DefectDojo will automatically mark the finding as a false positive if an equal finding (according to its dedupe algorithm) has been previously marked as a false positive on the same product. ATTENTION: Although the deduplication algorithm is used to determine if a finding should be marked as a false positive, this feature will not work if deduplication is enabled since it doesn't make sense to use both.",
    )
    retroactive_false_positive_history: Optional[StrictBool] = Field(
        default=None,
        description='(EXPERIMENTAL) FP History will also retroactively mark/unmark all existing equal findings in the same product as a false positives. Only works if the False Positive History feature is also enabled.',
    )
    url_prefix: Optional[Annotated[str, Field(strict=True, max_length=300)]] = Field(
        default=None, description="URL prefix if DefectDojo is installed in it's own virtual subdirectory."
    )
    team_name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    enable_product_grade: Optional[StrictBool] = Field(
        default=None, description='Displays a grade letter next to a product to show the overall health.'
    )
    product_grade_a: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(
        default=None, description="Percentage score for an 'A' >="
    )
    product_grade_b: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(
        default=None, description="Percentage score for a 'B' >="
    )
    product_grade_c: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(
        default=None, description="Percentage score for a 'C' >="
    )
    product_grade_d: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(
        default=None, description="Percentage score for a 'D' >="
    )
    product_grade_f: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(
        default=None, description="Percentage score for an 'F' <="
    )
    enable_product_tag_inheritance: Optional[StrictBool] = Field(
        default=None,
        description='Enables product tag inheritance globally for all products. Any tags added on a product will automatically be added to all Engagements, Tests, and Findings',
    )
    enable_benchmark: Optional[StrictBool] = Field(
        default=None,
        description='Enables Benchmarks such as the OWASP ASVS (Application Security Verification Standard)',
    )
    enable_similar_findings: Optional[StrictBool] = Field(
        default=None,
        description='Enable the query of similar findings on the view finding page. This feature can involve potentially large queries and negatively impact performance',
    )
    engagement_auto_close: Optional[StrictBool] = Field(
        default=None, description='Closes an engagement after 3 days (default) past due date including last update.'
    )
    engagement_auto_close_days: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(
        default=None,
        description='Closes an engagement after the specified number of days past due date including last update.',
    )
    enable_finding_sla: Optional[StrictBool] = Field(
        default=None, description="Enables Finding SLA's for time to remediate."
    )
    enable_notify_sla_active: Optional[StrictBool] = Field(
        default=None,
        description="Enables Notify when time to remediate according to Finding SLA's is breached for active Findings.",
    )
    enable_notify_sla_active_verified: Optional[StrictBool] = Field(
        default=None,
        description="Enables Notify when time to remediate according to Finding SLA's is breached for active, verified Findings.",
    )
    enable_notify_sla_jira_only: Optional[StrictBool] = Field(
        default=None,
        description="Enables Notify when time to remediate according to Finding SLA's is breached for Findings that are linked to JIRA issues. Notification is disabled for Findings not linked to JIRA issues",
    )
    enable_notify_sla_exponential_backoff: Optional[StrictBool] = Field(
        default=None,
        description='Enable an exponential backoff strategy for SLA breach notifications, e.g. 1, 2, 4, 8, etc. Otherwise it alerts every day',
    )
    allow_anonymous_survey_repsonse: Optional[StrictBool] = Field(
        default=None, description='Enable anyone with a link to the survey to answer a survey'
    )
    credentials: Optional[Annotated[str, Field(strict=True, max_length=3000)]] = None
    disclaimer_notifications: Optional[Annotated[str, Field(strict=True, max_length=3000)]] = Field(
        default=None, description='Include this custom disclaimer on all notifications'
    )
    disclaimer_reports: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(
        default=None, description='Include this custom disclaimer on generated reports'
    )
    disclaimer_reports_forced: Optional[StrictBool] = Field(
        default=None,
        description="Disclaimer will be added to all reports even if user didn't selected 'Include disclaimer'.",
    )
    disclaimer_notes: Optional[Annotated[str, Field(strict=True, max_length=3000)]] = Field(
        default=None, description='Include this custom disclaimer next to input form for notes'
    )
    risk_acceptance_form_default_days: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = (
        Field(default=None, description='Default expiry period for risk acceptance form.')
    )
    risk_acceptance_notify_before_expiration: Optional[
        Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]
    ] = Field(default=None, description='Notify X days before risk acceptance expires. Leave empty to disable.')
    enable_credentials: Optional[StrictBool] = Field(
        default=None, description='With this setting turned off, credentials will be disabled in the user interface.'
    )
    enable_questionnaires: Optional[StrictBool] = Field(
        default=None, description='With this setting turned off, questionnaires will be disabled in the user interface.'
    )
    enable_checklists: Optional[StrictBool] = Field(
        default=None, description='With this setting turned off, checklists will be disabled in the user interface.'
    )
    enable_endpoint_metadata_import: Optional[StrictBool] = Field(
        default=None,
        description='With this setting turned off, endpoint metadata import will be disabled in the user interface.',
    )
    enable_user_profile_editable: Optional[StrictBool] = Field(
        default=None, description='When turned on users can edit their profiles'
    )
    enable_product_tracking_files: Optional[StrictBool] = Field(
        default=None,
        description='With this setting turned off, the product tracking files will be disabled in the user interface.',
    )
    enable_finding_groups: Optional[StrictBool] = Field(
        default=None, description='With this setting turned off, the Finding Groups will be disabled.'
    )
    enable_ui_table_based_searching: Optional[StrictBool] = Field(
        default=None,
        description='With this setting enabled, table headings will contain sort buttons for the current page of data in addition to sorting buttons that consider data from all pages.',
    )
    enable_calendar: Optional[StrictBool] = Field(
        default=None, description='With this setting turned off, the Calendar will be disabled in the user interface.'
    )
    enable_cvss3_display: Optional[StrictBool] = Field(
        default=None, description='With this setting turned off, CVSS3 fields will be hidden in the user interface.'
    )
    enable_cvss4_display: Optional[StrictBool] = Field(
        default=None, description='With this setting turned off, CVSS4 fields will be hidden in the user interface.'
    )
    default_group_email_pattern: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None,
        description='New users will only be assigned to the default group, when their email address matches this regex pattern. This is optional condition.',
    )
    minimum_password_length: Optional[Annotated[int, Field(le=48, strict=True, ge=9)]] = Field(
        default=None, description='Requires user to set passwords greater than minimum length.'
    )
    maximum_password_length: Optional[Annotated[int, Field(le=48, strict=True, ge=9)]] = Field(
        default=None, description='Requires user to set passwords less than maximum length.'
    )
    number_character_required: Optional[StrictBool] = Field(
        default=None, description='Requires user passwords to contain at least one digit (0-9).'
    )
    special_character_required: Optional[StrictBool] = Field(
        default=None,
        description='Requires user passwords to contain at least one special character (()[]{}|\\`~!@#$%^&*_-+=;:\'",<>./?).',
    )
    lowercase_character_required: Optional[StrictBool] = Field(
        default=None, description='Requires user passwords to contain at least one lowercase letter (a-z).'
    )
    uppercase_character_required: Optional[StrictBool] = Field(
        default=None, description='Requires user passwords to contain at least one uppercase letter (A-Z).'
    )
    non_common_password_required: Optional[StrictBool] = Field(
        default=None, description='Requires user passwords to not be part of list of common passwords.'
    )
    api_expose_error_details: Optional[StrictBool] = Field(
        default=None, description='When turned on, the API will expose error details in the response.'
    )
    filter_string_matching: Optional[StrictBool] = Field(
        default=None,
        description='When turned on, all filter operations in the UI will require string matches rather than ID. This is a performance enhancement to avoid fetching objects unnecessarily.',
    )
    default_group: Optional[StrictInt] = Field(default=None, description='New users will be assigned to this group.')
    default_group_role: Optional[StrictInt] = Field(
        default=None, description='New users will be assigned to their default group with this role.'
    )
    __properties: ClassVar[List[str]] = [
        'enable_deduplication',
        'delete_duplicates',
        'max_dupes',
        'email_from',
        'enable_jira',
        'enable_jira_web_hook',
        'disable_jira_webhook_secret',
        'jira_webhook_secret',
        'jira_minimum_severity',
        'jira_labels',
        'add_vulnerability_id_to_jira_label',
        'enable_github',
        'enable_slack_notifications',
        'slack_channel',
        'slack_token',
        'slack_username',
        'enable_msteams_notifications',
        'msteams_url',
        'enable_mail_notifications',
        'mail_notifications_to',
        'enable_webhooks_notifications',
        'webhooks_notifications_timeout',
        'enforce_verified_status',
        'enforce_verified_status_jira',
        'enforce_verified_status_product_grading',
        'enforce_verified_status_metrics',
        'false_positive_history',
        'retroactive_false_positive_history',
        'url_prefix',
        'team_name',
        'enable_product_grade',
        'product_grade_a',
        'product_grade_b',
        'product_grade_c',
        'product_grade_d',
        'product_grade_f',
        'enable_product_tag_inheritance',
        'enable_benchmark',
        'enable_similar_findings',
        'engagement_auto_close',
        'engagement_auto_close_days',
        'enable_finding_sla',
        'enable_notify_sla_active',
        'enable_notify_sla_active_verified',
        'enable_notify_sla_jira_only',
        'enable_notify_sla_exponential_backoff',
        'allow_anonymous_survey_repsonse',
        'credentials',
        'disclaimer_notifications',
        'disclaimer_reports',
        'disclaimer_reports_forced',
        'disclaimer_notes',
        'risk_acceptance_form_default_days',
        'risk_acceptance_notify_before_expiration',
        'enable_credentials',
        'enable_questionnaires',
        'enable_checklists',
        'enable_endpoint_metadata_import',
        'enable_user_profile_editable',
        'enable_product_tracking_files',
        'enable_finding_groups',
        'enable_ui_table_based_searching',
        'enable_calendar',
        'enable_cvss3_display',
        'enable_cvss4_display',
        'default_group_email_pattern',
        'minimum_password_length',
        'maximum_password_length',
        'number_character_required',
        'special_character_required',
        'lowercase_character_required',
        'uppercase_character_required',
        'non_common_password_required',
        'api_expose_error_details',
        'filter_string_matching',
        'default_group',
        'default_group_role',
    ]

    @field_validator('jira_minimum_severity')
    def jira_minimum_severity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Critical', 'High', 'Medium', 'Low', 'Info', '']):
            raise ValueError("must be one of enum values ('Critical', 'High', 'Medium', 'Low', 'Info', '')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        defer_build=True,
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemSettingsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_dupes (nullable) is None
        # and model_fields_set contains the field
        if self.max_dupes is None and 'max_dupes' in self.model_fields_set:
            _dict['max_dupes'] = None

        # set to None if jira_webhook_secret (nullable) is None
        # and model_fields_set contains the field
        if self.jira_webhook_secret is None and 'jira_webhook_secret' in self.model_fields_set:
            _dict['jira_webhook_secret'] = None

        # set to None if jira_minimum_severity (nullable) is None
        # and model_fields_set contains the field
        if self.jira_minimum_severity is None and 'jira_minimum_severity' in self.model_fields_set:
            _dict['jira_minimum_severity'] = None

        # set to None if jira_labels (nullable) is None
        # and model_fields_set contains the field
        if self.jira_labels is None and 'jira_labels' in self.model_fields_set:
            _dict['jira_labels'] = None

        # set to None if risk_acceptance_form_default_days (nullable) is None
        # and model_fields_set contains the field
        if (
            self.risk_acceptance_form_default_days is None
            and 'risk_acceptance_form_default_days' in self.model_fields_set
        ):
            _dict['risk_acceptance_form_default_days'] = None

        # set to None if risk_acceptance_notify_before_expiration (nullable) is None
        # and model_fields_set contains the field
        if (
            self.risk_acceptance_notify_before_expiration is None
            and 'risk_acceptance_notify_before_expiration' in self.model_fields_set
        ):
            _dict['risk_acceptance_notify_before_expiration'] = None

        # set to None if default_group (nullable) is None
        # and model_fields_set contains the field
        if self.default_group is None and 'default_group' in self.model_fields_set:
            _dict['default_group'] = None

        # set to None if default_group_role (nullable) is None
        # and model_fields_set contains the field
        if self.default_group_role is None and 'default_group_role' in self.model_fields_set:
            _dict['default_group_role'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemSettingsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'enable_deduplication': obj.get('enable_deduplication'),
                'delete_duplicates': obj.get('delete_duplicates'),
                'max_dupes': obj.get('max_dupes'),
                'email_from': obj.get('email_from'),
                'enable_jira': obj.get('enable_jira'),
                'enable_jira_web_hook': obj.get('enable_jira_web_hook'),
                'disable_jira_webhook_secret': obj.get('disable_jira_webhook_secret'),
                'jira_webhook_secret': obj.get('jira_webhook_secret'),
                'jira_minimum_severity': obj.get('jira_minimum_severity'),
                'jira_labels': obj.get('jira_labels'),
                'add_vulnerability_id_to_jira_label': obj.get('add_vulnerability_id_to_jira_label'),
                'enable_github': obj.get('enable_github'),
                'enable_slack_notifications': obj.get('enable_slack_notifications'),
                'slack_channel': obj.get('slack_channel'),
                'slack_token': obj.get('slack_token'),
                'slack_username': obj.get('slack_username'),
                'enable_msteams_notifications': obj.get('enable_msteams_notifications'),
                'msteams_url': obj.get('msteams_url'),
                'enable_mail_notifications': obj.get('enable_mail_notifications'),
                'mail_notifications_to': obj.get('mail_notifications_to'),
                'enable_webhooks_notifications': obj.get('enable_webhooks_notifications'),
                'webhooks_notifications_timeout': obj.get('webhooks_notifications_timeout'),
                'enforce_verified_status': obj.get('enforce_verified_status'),
                'enforce_verified_status_jira': obj.get('enforce_verified_status_jira'),
                'enforce_verified_status_product_grading': obj.get('enforce_verified_status_product_grading'),
                'enforce_verified_status_metrics': obj.get('enforce_verified_status_metrics'),
                'false_positive_history': obj.get('false_positive_history'),
                'retroactive_false_positive_history': obj.get('retroactive_false_positive_history'),
                'url_prefix': obj.get('url_prefix'),
                'team_name': obj.get('team_name'),
                'enable_product_grade': obj.get('enable_product_grade'),
                'product_grade_a': obj.get('product_grade_a'),
                'product_grade_b': obj.get('product_grade_b'),
                'product_grade_c': obj.get('product_grade_c'),
                'product_grade_d': obj.get('product_grade_d'),
                'product_grade_f': obj.get('product_grade_f'),
                'enable_product_tag_inheritance': obj.get('enable_product_tag_inheritance'),
                'enable_benchmark': obj.get('enable_benchmark'),
                'enable_similar_findings': obj.get('enable_similar_findings'),
                'engagement_auto_close': obj.get('engagement_auto_close'),
                'engagement_auto_close_days': obj.get('engagement_auto_close_days'),
                'enable_finding_sla': obj.get('enable_finding_sla'),
                'enable_notify_sla_active': obj.get('enable_notify_sla_active'),
                'enable_notify_sla_active_verified': obj.get('enable_notify_sla_active_verified'),
                'enable_notify_sla_jira_only': obj.get('enable_notify_sla_jira_only'),
                'enable_notify_sla_exponential_backoff': obj.get('enable_notify_sla_exponential_backoff'),
                'allow_anonymous_survey_repsonse': obj.get('allow_anonymous_survey_repsonse'),
                'credentials': obj.get('credentials'),
                'disclaimer_notifications': obj.get('disclaimer_notifications'),
                'disclaimer_reports': obj.get('disclaimer_reports'),
                'disclaimer_reports_forced': obj.get('disclaimer_reports_forced'),
                'disclaimer_notes': obj.get('disclaimer_notes'),
                'risk_acceptance_form_default_days': obj.get('risk_acceptance_form_default_days'),
                'risk_acceptance_notify_before_expiration': obj.get('risk_acceptance_notify_before_expiration'),
                'enable_credentials': obj.get('enable_credentials'),
                'enable_questionnaires': obj.get('enable_questionnaires'),
                'enable_checklists': obj.get('enable_checklists'),
                'enable_endpoint_metadata_import': obj.get('enable_endpoint_metadata_import'),
                'enable_user_profile_editable': obj.get('enable_user_profile_editable'),
                'enable_product_tracking_files': obj.get('enable_product_tracking_files'),
                'enable_finding_groups': obj.get('enable_finding_groups'),
                'enable_ui_table_based_searching': obj.get('enable_ui_table_based_searching'),
                'enable_calendar': obj.get('enable_calendar'),
                'enable_cvss3_display': obj.get('enable_cvss3_display'),
                'enable_cvss4_display': obj.get('enable_cvss4_display'),
                'default_group_email_pattern': obj.get('default_group_email_pattern'),
                'minimum_password_length': obj.get('minimum_password_length'),
                'maximum_password_length': obj.get('maximum_password_length'),
                'number_character_required': obj.get('number_character_required'),
                'special_character_required': obj.get('special_character_required'),
                'lowercase_character_required': obj.get('lowercase_character_required'),
                'uppercase_character_required': obj.get('uppercase_character_required'),
                'non_common_password_required': obj.get('non_common_password_required'),
                'api_expose_error_details': obj.get('api_expose_error_details'),
                'filter_string_matching': obj.get('filter_string_matching'),
                'default_group': obj.get('default_group'),
                'default_group_role': obj.get('default_group_role'),
            }
        )
        return _obj
