name: 🧪 tests

on:
  workflow_call:
  push:
    branches-ignore:
      # these are already tested by publish-dev
      - dev
      - dev/*
      - dev-*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv requirements --dev > reqs.txt
          pip install -r reqs.txt

      - name: Lint check
        run: |
          make lint-check

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv requirements --dev > reqs.txt
          pip install -r reqs.txt

      - name: Run unit tests
        run: |
          make test
      
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
      
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv requirements --dev > reqs.txt
          pip install -r reqs.txt

      - name: Run e2e tests
        run: |
          make test-e2e
